spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dbcepmanager
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/config/liquibase/master.xml
    enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
api:
  webclient:
    base-url: https://viacep.com.br/ws/
server:
  port: 8080
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    url: /api-docs
    enabled: true
